/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedVoteIndexRouteImport } from './routes/_authenticated/vote.index'
import { Route as AuthenticatedVoteProjectIdRouteImport } from './routes/_authenticated/vote.$projectId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoteIndexRoute = AuthenticatedVoteIndexRouteImport.update({
  id: '/vote/',
  path: '/vote/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVoteProjectIdRoute =
  AuthenticatedVoteProjectIdRouteImport.update({
    id: '/vote/$projectId',
    path: '/vote/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/results': typeof AuthenticatedResultsRoute
  '/vote/$projectId': typeof AuthenticatedVoteProjectIdRoute
  '/vote/': typeof AuthenticatedVoteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/results': typeof AuthenticatedResultsRoute
  '/vote/$projectId': typeof AuthenticatedVoteProjectIdRoute
  '/vote': typeof AuthenticatedVoteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/vote/$projectId': typeof AuthenticatedVoteProjectIdRoute
  '/_authenticated/vote/': typeof AuthenticatedVoteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/results' | '/vote/$projectId' | '/vote/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/results' | '/vote/$projectId' | '/vote'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/results'
    | '/_authenticated/vote/$projectId'
    | '/_authenticated/vote/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vote/': {
      id: '/_authenticated/vote/'
      path: '/vote'
      fullPath: '/vote/'
      preLoaderRoute: typeof AuthenticatedVoteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vote/$projectId': {
      id: '/_authenticated/vote/$projectId'
      path: '/vote/$projectId'
      fullPath: '/vote/$projectId'
      preLoaderRoute: typeof AuthenticatedVoteProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedVoteProjectIdRoute: typeof AuthenticatedVoteProjectIdRoute
  AuthenticatedVoteIndexRoute: typeof AuthenticatedVoteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedVoteProjectIdRoute: AuthenticatedVoteProjectIdRoute,
  AuthenticatedVoteIndexRoute: AuthenticatedVoteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
